### ISSUE TITLE
Method upload_template_xml from called from hydra-server doesn't exist

### ISSUE THREAD

**Issue by robhoney** [hydraplatform/hydra-server#18]
The method referenced in template.py below (_template.upload_template_xml_) does not exist in hydra base. It looks as if it has been renamed there (_import_template_xml_), so either it needs to be renamed to match in hydra server or the one in hydra base (_import_template_xml_) should be renamed back to _upload_template_xml_.

```
@rpc(Unicode, _returns=Template)
    def upload_template_xml(ctx, template_xml):
        """
            Add the template, type and typeattrs described
            in an XML file.
            Delete type, typeattr entries in the DB that are not in the XML file
            The assumption is that they have been deleted and are no longer required.
        """
        tmpl_i = template.upload_template_xml(template_xml,
                                              **ctx.in_header.__dict__)
```

**Comment by knoxsp** [comment]
This has been replaced by 'import_template_xml'
